//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "calendars")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub service_id: i64,
    pub monday: Option<i8>,
    pub tuesday: Option<i8>,
    pub wednesday: Option<i8>,
    pub thursday: Option<i8>,
    pub friday: Option<i8>,
    pub saturday: Option<i8>,
    pub sunday: Option<i8>,
    pub start_date: Option<String>,
    pub end_date: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
