//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "shapes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub shape_id: i32,
    #[sea_orm(column_type = "Double")]
    pub shape_pt_lat: f64,
    #[sea_orm(column_type = "Double")]
    pub shape_pt_lon: f64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub shape_pt_sequence: i32,
    #[sea_orm(column_type = "Double")]
    pub shape_dist_traveled: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
