//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "stops")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub stop_id: i64,
    pub stop_code: Option<i64>,
    pub stop_name: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub stop_lat: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub stop_lon: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
