# fly.toml app configuration file generated for roundhouse-prod on 2024-01-25T22:25:55-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'roundhouse-prod'
primary_region = 'atl'

[build]

[env]
  LOCO_ENV = 'production'
  RH_PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[mounts]
  source="mio_prod_vol"
  destination="/mnt/mio_prod_vol"
